#!/bin/bash
# Copyright (c) 2012 Travis Cross <tc@traviscross.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

type="$1"
ref="$2"

if [ $# -lt 2 ]; then
  echo "usage: $0 type ref"
  exit 1
fi

burl="http://xml.resource.org/public/rfc/bibxml2/"
pfx="reference"
case "$type" in
  rfc)
    burl="http://xml.resource.org/public/rfc/bibxml/"
    doc="${pfx}.RFC.${ref}.xml"
    ;;
  i-d)
    burl="http://xml.resource.org/public/rfc/bibxml3/"
    doc="${pfx}.I-D.${ref}.xml"
    ;;
  w3c)
    burl="http://xml.resource.org/public/rfc/bibxml4/"
    doc="${pfx}.W3C.${ref}.xml"
    ;;
  jsf)
    burl="http://www.xmpp.org/extensions/refs/"
    doc="${pfx}.XSF.XEP-${ref}.xml"
    ;;
  3gpp)
    burl="http://xml.resource.org/public/rfc/bibxml5/"
    doc="${pfx}.3GPP.${ref}.xml"
    ;;
  misc)
    burl="http://xml.resource.org/public/rfc/bibxml2/"
    doc="${pfx}.${ref}.xml"
    ;;
esac

wget -N $burl/$doc

